#ifndef __CONFTIG_H__
#define __CONFTIG_H__
#define WIDTH_SCREEN 640
#define HEIGHT_SCREEN 480

//#define FPS_LIMIT 30.f
//#define FPS_DELAY 1000.0f / FPS_LIMIT

/******SPRITES*****/
///TIPO_NOMBRE(archivo)_DESCRIPCION
#define MODULO_MINAVE_NAVE   0
//#define MODULO_MENU_FONDO    1
//#define MODULO_ENEMIGO_NAVE  2
//#define MODULO_TEXTO_TITULO  3
//#define MODULO_TEXTO_NOMBRE  4
//#define MODULO_TEXTO_OPCION1 5
//#define MODULO_TEXTO_OPCION2 6
//#define MODULO_TEXTO_OPCION1_SELECCION 7
//#define MODULO_TEXTO_OPCION2_SELECCION 8
//
//#define MENU_NUMERO_ELEMNTOS  MODULO_TEXTO_OPCION1_SELECCION-MODULO_TEXTO_OPCION1

#endif